import { describe, expect, it } from 'vitest';

import { Event } from '@types';

import { ParseInput } from '../ParseInput';

describe('should parse input', () => {
  it('should parse with multiple kyoku', () => {
    const input: unknown = [
      {
        type: 'start_game',
        names: ['Aさん', 'Bさん', 'Cさん', 'Dさん'],
        kyoku_first: 0,
        aka_flag: true,
      },
      {
        type: 'start_kyoku',
        bakaze: 'E',
        dora_marker: 'P',
        kyoku: 1,
        honba: 0,
        kyotaku: 0,
        oya: 0,
        scores: [25000, 25000, 25000, 25000],
        tehais: [
          [
            '6p',
            '3s',
            'N',
            '6m',
            '9s',
            '1p',
            '5m',
            'P',
            '7m',
            '3s',
            '3p',
            '5m',
            '4m',
          ],
          [
            'E',
            '8m',
            '5pr',
            '5s',
            '1p',
            '1s',
            '9p',
            'F',
            '1s',
            'N',
            '4p',
            'P',
            '3s',
          ],
          [
            '6m',
            'N',
            '2s',
            '5s',
            '2s',
            '4m',
            'C',
            '2p',
            '5p',
            '8p',
            '2m',
            '3m',
            'W',
          ],
          [
            '8s',
            '6m',
            '1m',
            '8m',
            '2m',
            '4s',
            '5sr',
            '3p',
            '6p',
            '6s',
            '9m',
            '3m',
            '2s',
          ],
        ],
      },
      {
        type: 'tsumo',
        actor: 0,
        pai: 'N',
      },
      {
        type: 'end_kyoku',
      },
      {
        type: 'start_kyoku',
        bakaze: 'E',
        dora_marker: 'P',
        kyoku: 1,
        honba: 0,
        kyotaku: 0,
        oya: 0,
        scores: [25000, 25000, 25000, 25000],
        tehais: [
          [
            '6p',
            '3s',
            'N',
            '6m',
            '9s',
            '1p',
            '5m',
            'P',
            '7m',
            '3s',
            '3p',
            '5m',
            '4m',
          ],
          [
            'E',
            '8m',
            '5pr',
            '5s',
            '1p',
            '1s',
            '9p',
            'F',
            '1s',
            'N',
            '4p',
            'P',
            '3s',
          ],
          [
            '6m',
            'N',
            '2s',
            '5s',
            '2s',
            '4m',
            'C',
            '2p',
            '5p',
            '8p',
            '2m',
            '3m',
            'W',
          ],
          [
            '8s',
            '6m',
            '1m',
            '8m',
            '2m',
            '4s',
            '5sr',
            '3p',
            '6p',
            '6s',
            '9m',
            '3m',
            '2s',
          ],
        ],
      },
      {
        type: 'tsumo',
        actor: 0,
        pai: 'N',
      },
      {
        type: 'end_kyoku',
      },
      {
        type: 'end_game',
      },
    ];

    const actual = ParseInput(input);
    const expected: Event[] = [
      {
        type: 'start_game',
        names: ['Aさん', 'Bさん', 'Cさん', 'Dさん'],
        kyokuFirst: 0,
        akaFlag: true,
      },
      {
        type: 'start_kyoku',
        bakaze: 'E',
        doraMarker: 'P',
        kyoku: 1,
        honba: 0,
        kyotaku: 0,
        oya: 0,
        scores: [25000, 25000, 25000, 25000],
        tehais: [
          [
            '6p',
            '3s',
            'N',
            '6m',
            '9s',
            '1p',
            '5m',
            'P',
            '7m',
            '3s',
            '3p',
            '5m',
            '4m',
          ],
          [
            'E',
            '8m',
            '5pr',
            '5s',
            '1p',
            '1s',
            '9p',
            'F',
            '1s',
            'N',
            '4p',
            'P',
            '3s',
          ],
          [
            '6m',
            'N',
            '2s',
            '5s',
            '2s',
            '4m',
            'C',
            '2p',
            '5p',
            '8p',
            '2m',
            '3m',
            'W',
          ],
          [
            '8s',
            '6m',
            '1m',
            '8m',
            '2m',
            '4s',
            '5sr',
            '3p',
            '6p',
            '6s',
            '9m',
            '3m',
            '2s',
          ],
        ],
      },
      {
        type: 'tsumo',
        actor: 0,
        pai: 'N',
      },
      {
        type: 'end_kyoku',
      },
      {
        type: 'start_kyoku',
        bakaze: 'E',
        doraMarker: 'P',
        kyoku: 1,
        honba: 0,
        kyotaku: 0,
        oya: 0,
        scores: [25000, 25000, 25000, 25000],
        tehais: [
          [
            '6p',
            '3s',
            'N',
            '6m',
            '9s',
            '1p',
            '5m',
            'P',
            '7m',
            '3s',
            '3p',
            '5m',
            '4m',
          ],
          [
            'E',
            '8m',
            '5pr',
            '5s',
            '1p',
            '1s',
            '9p',
            'F',
            '1s',
            'N',
            '4p',
            'P',
            '3s',
          ],
          [
            '6m',
            'N',
            '2s',
            '5s',
            '2s',
            '4m',
            'C',
            '2p',
            '5p',
            '8p',
            '2m',
            '3m',
            'W',
          ],
          [
            '8s',
            '6m',
            '1m',
            '8m',
            '2m',
            '4s',
            '5sr',
            '3p',
            '6p',
            '6s',
            '9m',
            '3m',
            '2s',
          ],
        ],
      },
      {
        type: 'tsumo',
        actor: 0,
        pai: 'N',
      },
      {
        type: 'end_kyoku',
      },
      {
        type: 'end_game',
      },
    ];

    expect(actual).toEqual(expected);
  });
});
